name: Feature request
description: Propose a new feature or meaningful enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem are you trying to solve?
      placeholder: "It is hard for beginners to..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the best solution you have in mind.
      placeholder: "Add a guided page that..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other options did you consider?
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: Learner impact
      description: Who benefits, and how?
      placeholder: "Beginners can complete onboarding in 10 minutes."
    validations:
      required: true
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: I checked existing issues and discussions first.
          required: true
